---
# This file contains the defaults for all optional, overridable values

istio:
  # -- A whitelist of external services that your application requires connection to.
  # The whitelist applies to the entire namespace in which this chart is installed.
  # [These services](https://github.com/variant-inc/iaac-eks/blob/master/scripts/istio/service-entries.eps#L8) are globally whitelisted and do not require declaration.
  # See [egress](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/egress).
  # See [Ingress](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/ingress) for more Istio details.
  egress: []

# @ignored
# -- (list) https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
imagePullSecrets: []

# @ignored
serviceAccount:
  # -- (string) Optional ARN of the IAM role to be assumed by your application.
  # If your API requires access to any AWS services, a role should be created in AWS IAM.
  # This role should have an inline policy that describes the permissions your API needs (connect to RDS, publish to an SNS topic, read from an SQS queue, etc.).
  # [RoleArn](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/rolearn)
  roleArn:

# -- (map) Security Context for pods
podSecurityContext:
  # -- The files created in the container will be created with this gid
  # `65534` is a `nobody` group
  fsGroup: 65534

# -- (map) Security Context for containers
securityContext:
  # -- (int) Runs as numeric user
  runAsUser:
  # -- (int) Runs as numeric user
  runAsGroup:
  # -- Drop All capabilities
  capabilities:
    drop:
      - ALL
  # @ignored
  # -- Runs as non root. Must use numeric User in container
  runAsNonRoot: true
  # @ignored
  # -- (bool) Setting it to false ensures that no child process of a container can gain more privileges than its parent
  allowPrivilegeEscalation: false
  # @ignored
  # -- (bool) Requires that containers must run with a read-only root filesystem (i.e. no writable layer)
  readOnlyRootFilesystem: false

cronJob:
  # -- Cron Style Schedule. For help check https://crontab.guru/
  schedule:
  image:
    # -- (string) IfNotPresent, Always, Never
    pullPolicy: IfNotPresent
    # -- (string) The full URL of the image to be deployed containing the HTTP API application
    tag:
  # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources:
    limits:
      # -- (int) Limits CPU, intentionally set to null, can't be overridden
      cpu: null
      # -- (string) Limits Memory
      memory: 768Mi
    requests:
      # -- (float) Requests CPU
      cpu: .1
      # -- (string) Request memory
      memory: 384Mi
  # -- (string) https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy
  concurrencyPolicy: Replace
  # -- (list) full path to the job script to execute. https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
  command:
  # -- (bool) https://kubernetes.io/blog/2021/04/12/introducing-suspended-jobs/
  suspend: false

# -- (map) https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# -- A list of secrets to configure to make available to your API.
# Create your secret in AWS Secrets Manager as plain text.
# Full contents of this secret will be mounted as a file your application can read to /app/secrets/{name}
# See [AWS Secrets](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/environment_variables) for more details.
# @default -- Example: `[{ "name": "eng-secret-in-aws", "type": "" }]`
awsSecrets: []

# @ignored
# -- (string) Value for a [label](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) named `revision`
# that will be applied to all objects created by a specific chart installation.
# Strongly encouraged that this value corresponds to 1 of: Octopus package version, short-SHA of the commit, Octopus release version
revision:

# -- (map) User defined secret variables are implemented here.
# [More Information](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/environment_variables)
# @default -- Example: `foo: bar`
secretVars: {}

# -- (map) User defined environment variables are implemented here.
# [More Information](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/environment_variables)
# @default -- Example: `bar: foo`
configVars: {}

# @ignored
# -- Node labels for pod assignment
# [NodeSelector](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/nodeselector)
nodeSelector: {}

# @ignored
# --  Tolerations for pod assignment
# [Tolerations](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/tolerations)
tolerations: []

# Karpenter Provisioner Variables. https://karpenter.sh/v0.6.0/provisioner/
node:
  # -- Flag to determine whether or not custom nodes will be provisioned.
  create: false
  # -- The EC2 Instance Type for your custom nodes.
  instanceType:
  # -- If nil, the feature is disabled, nodes will never expire
  consolidateAfter:
  # -- The amount of time a Node can live on the cluster before being removed.
  expireAfter: 1h

# @ignored
# -- Tags to be applied to custom node provisioner and labels
tags: {}

# -- Use Never by default for jobs so new pod is created on failure instead of restarting containers
restartPolicy: Never

usxpressCACertBundle:
  # -- (bool) If set to true, volume mounts the certificate from the custom-ca-certs secret
  enabled: true
  # -- (string)  The cert is mounted to the default path mentioned. The path can also be changed.
  certMountPath: /etc/ssl/certs/

# @ignored
# For setting up otel sidecar for auto instrumentation
otel:
  # Enable OTel sidecar
  enabled: false
  # Language of the application
  language: sdk
