deployment:
  image:
    tag: 064859874041.dkr.ecr.us-east-2.amazonaws.com/lazy-helm-charts/variant-api:v0.3
revision: testing

istio:
  enabled: true
  ingress:
    host: dpl-drivevariant.com
service:
  targetPort: 5000

configVars:
  PLAIN_CONFIG: foo

secretVars:
  SECRET_CONFIG: secret
  SOMETHING: else

configMaps:
  - test-existing

awsSecrets:
  - name: devops-playground-rds-creds
