suite: Chart defaults
tests:
  - it: should be internal only
    release:
      name: test
    set:
      deployment.image.tag: tag
      revision: revision
      istio.ingress.host: host
      tags:
        octopus_tags:
          project: test
          space: default
          environment: dev
          project_group: default group
          release_channel: test
        user_tags:
          team: devops
          purpose: test
          owner: devops
    asserts:
      - template: virtual-service.yaml
        containsDocument:
          apiVersion: networking.istio.io/v1alpha3
          kind: VirtualService
          name: test-internal
      - template: virtual-service.yaml
        hasDocuments:
          count: 2