suite: Chart defaults
tests:
  - it: should be internal only
    release:
      name: test
    set:
      deployment.image.tag: tag
      revision: revision
      istio.ingress.host: host
      tags:
        octopus/project: test
        octopus/space: default
        octopus/environment: dev
        octopus/project_group: default group
        octopus/release_channel: test
        team: devops
        purpose: test
        owner: devops
    asserts:
      - template: virtual-service.yaml
        containsDocument:
          apiVersion: networking.istio.io/v1alpha3
          kind: VirtualService
          name: test-internal
      - template: virtual-service.yaml
        hasDocuments:
          count: 2