suite: Chart defaults
templates:
  - authorization.yaml
tests:
  - it: should whitelist
    release:
      name: test
    documentIndex: 0
    set:
      revision: revision
      istio.ingress.host: host
      deployment.image.tag: tag
      tags:
        octopus/project: test
        octopus/space: default
        octopus/environment: dev
        octopus/project_group: default group
        octopus/release_channel: test
        team: devops
        purpose: test
        owner: devops
      authentication:
        enabled: true
        server: trustme.com
        jwksUri: "https://login.microsoftonline.com/common/discovery/keys"
      authorization:
        rules:
          to:
            - operation:
                methods: "GET"
                paths: "/swagger"
    asserts:
      - contains:
          path: spec.rules[1].to
          content:
            operation:
              methods: ["GET"]
              paths: ["/swagger"]