suite: Chart defaults
templates:
  - authorization.yaml
tests:
  - it: should whitelist
    release:
      name: test
    documentIndex: 0
    set:
      revision: revision
      istio.ingress.host: host
      deployment.image.tag: tag
      tags:
        octopus_tags:
          project: test
          space: default
          environment: dev
          project_group: default group
          release_channel: test
        user_tags:
          team: devops
          purpose: test
          owner: devops
      authentication:
        enabled: true
        server: trustme.com
      authorization:
        rules:
          to:
            - operation:
                methods: "GET"
                paths: "/swagger"
    asserts:
      - contains:
          path: spec.rules[1].to
          content:
            operation:
              methods: ["GET"]
              paths: ["/swagger"]