suite: Chart defaults
tests:
  - it: should work
    release:
      name: test
    set:
      cronJob.image.tag: busybox:latest
      cronJob.schedule: "*/2 * * * *"
      revision: revision
      cronJob.command: 
        - /bin/echo
        - "Hello from unit test"
    asserts:
      - template: cron.yaml
        containsDocument:
          apiVersion: batch/v1beta1
          kind: CronJob
          name: test
      - template: cron.yaml
        hasDocuments:
          count: 2
  - it: should have provisioner
    release:
      name: test
    set:
      cronJob.image.tag: busybox:latest
      cronJob.schedule: "*/2 * * * *"
      revision: revision
      cronJob.command: 
        - /bin/echo
        - "Hello from unit test"
      node:
        create: true
        instanceType: t3.medium
      tolerations:
        - key: "lee-test"
      nodeSelector:
        purpose: unit-test
        env: dpl
      tags:
        owner: platform-infrastructure
    asserts:
      - template: provisioner.yaml
        containsDocument:
          apiVersion: karpenter.sh/v1alpha5
          kind: Provisioner
          name: test
      - template: provisioner.yaml
        hasDocuments:
          count: 1