---
suite: Chart defaults
tests:
  - it: should work
    release:
      name: test
    set:
      cronJob.image.tag: busybox:latest
      cronJob.schedule: "*/2 * * * *"
      revision: revision
      tags:
        octopus/project: test
        octopus/space: default
        octopus/environment: dev
        octopus/project_group: default group
        octopus/release_channel: test
        team: devops
        purpose: test
        owner: devops
      cronJob.command:
        - /bin/echo
        - "Hello from unit test"
    asserts:
      - template: cron.yaml
        containsDocument:
          apiVersion: batch/v1
          kind: CronJob
          name: test
      - template: cron.yaml
        hasDocuments:
          count: 2
  - it: should have nodepool
    release:
      name: test
      namespace: test
    set:
      cronJob.image.tag: busybox:latest
      cronJob.schedule: "*/2 * * * *"
      revision: revision
      cronJob.command:
        - /bin/echo
        - "Hello from unit test"
      node:
        create: true
        instanceType: t3.medium
      tolerations:
        - key: "lee-test"
      nodeSelector:
        purpose: unit-test
        env: dpl
      tags:
        owner: platform-infrastructure
        octopus/project: test
        octopus/space: default
        octopus/environment: dev
        octopus/project_group: default group
        octopus/release_channel: test
        team: devops
        purpose: test
    asserts:
      - template: nodepool.yaml
        containsDocument:
          apiVersion: karpenter.sh/v1beta1
          kind: NodePool
          name: test-test
      - template: nodepool.yaml
        hasDocuments:
          count: 1
  - it: defaults to Never restart policy
    release:
      name: test
    set:
      cronJob.image.tag: busybox:latest
      cronJob.schedule: "*/2 * * * *"
      revision: revision
      cronJob.command:
        - /bin/echo
        - "Hello from unit test"
    asserts:
      - template: cron.yaml
        documentIndex: 0
        equal:
          path: spec.jobTemplate.spec.template.spec.restartPolicy
          value: Never
