{{- $fullName := (include "chart.fullname" .) -}}
{{- $labels := (include "library.chart.labels" .) -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  schedule: {{  required "cronJob.schedule is required" .Values.cronJob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronJob.concurrencyPolicy }}
  startingDeadlineSeconds: {{ .Values.cronJob.startingDeadlineSeconds  }}
  suspend: {{ .Values.cronJob.suspend }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec: {{ include "chart.jobspec" . | nindent 6 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}-test
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    {{- $labels | nindent 4 }}
spec: {{ include "chart.jobspec" . | nindent 2 }}
