{{- if .Values.node.create }}
{{- $fullName := (include "chart.fullname" .) -}}
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ $fullName }}
spec:
  # If nil, the feature is disabled, nodes will never expire
  # 30 Days Default = 60 * 60 * 24 * 30 Seconds;
  ttlSecondsUntilExpired: {{ .Values.node.ttlSecondsUntilExpired}} 

  # If nil, the feature is disabled, nodes will never scale down due to low utilization
  ttlSecondsAfterEmpty: {{ .Values.node.ttlSecondsAfterEmpty }}

  # Provisioned nodes will have these taints
  # Taints may prevent pods from scheduling if they are not tolerated
  taints:
    {{- range .Values.tolerations }}
    - key: {{ required "Key is required for tolerations" .key | quote }}
      effect: {{ .effect | default "NoSchedule" | quote }}
    {{- end }}

  # Labels are arbitrary key-values that are applied to all nodes
  labels:
    {{- range $key, $value := .Values.nodeSelector }}
    {{ $key }}: {{ $value }}
    {{- end }}

  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: [{{ .Values.node.instanceType | quote }}]
  # These fields vary per cloud provider, see your cloud provider specific documentation
  provider:
    subnetSelector:
      kubernetes.io/role/internal-elb: '1'
    securityGroupSelector:
      kubernetes.io/cluster/{{ .Values.CLUSTER_NAME }}: '*'
    tags: {{ required "Tags are required to create custom nodes" .Values.tags | toYaml | nindent 6 }}
{{- end }}