{{- if .Values.node.create }}
{{- $fullName := (include "chart.fullname" .) -}}
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ .Release.Namespace }}-{{ $fullName }}
spec:
  # If nil, the feature is disabled, nodes will never expire
  # 30 Days Default = 60 * 60 * 24 * 30 Seconds;
  ttlSecondsUntilExpired: {{ .Values.node.ttlSecondsUntilExpired}} 

  # If nil, the feature is disabled, nodes will never scale down due to low utilization
  ttlSecondsAfterEmpty: {{ .Values.node.ttlSecondsAfterEmpty }}

  # Provisioned nodes will have these taints
  # Taints may prevent pods from scheduling if they are not tolerated
  taints:
    - key: "namespace"
      value: {{ .Release.Namespace | quote }}
      effect: "NoSchedule"
    {{- range .Values.tolerations }}
    - key: {{ required "Key is required for tolerations" .key | quote }}
      effect: {{ .effect | default "NoSchedule" | quote }}
    {{- end }}

  # Labels are arbitrary key-values that are applied to all nodes
  labels:
    {{- range $key, $value := .Values.nodeSelector }}
    {{ $key }}: {{ $value }}
    {{- end }}
    cloudops.io/namespace: {{ .Release.Namespace }}

  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values:
        - on-demand
    - key: "kubernetes.io/arch"
      operator: In
      values:
        - amd64
    {{- if .Values.node.instanceType }}
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: [{{ .Values.node.instanceType | quote }}]
    {{- end }}
  providerRef:
    name: bottlerocket
{{- end }}