suite: Chart defaults
tests:
  - it: should be internal
    release:
      name: test
    set:
      deployment.image.tag: tag
      revision: abc
      tags:
        owner: platform-infrastructure
        octopus/project: test
        octopus/space: default
        octopus/environment: dev
        octopus/project_group: default group
        octopus/release_channel: test
        team: devops
        purpose: test
      livenessProbe:
        exec:
          command:
            - /bin/echo
            - "hello liveness"
      readinessProbe:
        exec:
          command:
            - /bin/echo
            - "hello readiness"
      istio.ingress.public: true
      istio.ingress.host: dpl-drivevariant.com
      configVars:
        foo: bar
        color: red
    asserts:
      - template: virtual-service.yaml
        containsDocument:
          kind: VirtualService
          apiVersion: networking.istio.io/v1alpha3
          name: test-internal
      - template: virtual-service.yaml
        hasDocuments:
          count: 2
  - it: should be public and internal
    release:
      name: test
    set:
      deployment.image.tag: tag
      revision: abc
      tags:
        owner: platform-infrastructure
        octopus/project: test
        octopus/space: default
        octopus/environment: dev
        octopus/project_group: default group
        octopus/release_channel: test
        team: devops
      istio.ingress.host: dpl-drivevariant.com
      livenessProbe:
        exec:
          command:
            - /bin/echo
            - "hello liveness"
      readinessProbe:
        exec:
          command:
            - /bin/echo
            - "hello readiness"
    asserts:
      - template: virtual-service.yaml
        containsDocument:
          kind: VirtualService
          apiVersion: networking.istio.io/v1alpha3
          name: test-internal
      - template: virtual-service.yaml
        hasDocuments:
          count: 1