apiVersion: v2
name: variant-ui
description: A Helm chart for a web UI configuration

version: 1.0.2


kubeVersion: "^1.7.1-0"
home: https://www.drivevariant.com/
icon: https://github.com/variant-inc/in-helm-charts/raw/gh-pages/assets/variant-logo.svg
sources:
  - https://github.com/variant-inc
maintainers:
  - name: vibindaniel
    email: vibind@drivevariant.com
  - name: salyateem13
    email: samira@drivevariant.com

