---
apiVersion: v2
name: variant-ui
description: A Helm chart for a web UI configuration

version: 1.5.3

kubeVersion: "^1.7.1-0"
home: https://www.drivevariant.com/
icon: https://github.com/variant-inc/in-helm-charts/raw/gh-pages/assets/variant-logo.svg
sources:
  - https://github.com/variant-inc
maintainers:
  - name: vibindaniel
    email: vibind@drivevariant.com
  - name: salyateem13
    email: samira@drivevariant.com
  - name: LeeHughsVariant
    email: leeh@drivevariant.com

dependencies:
  - name: library
    repository: file://../library
    version: 0.1.0
  - name: oauth2-proxy
    version: "~6.12.0"
    # alias: oauth2Proxy
    repository: https://oauth2-proxy.github.io/manifests
    condition: oauth2-proxy.enabled
