# Default values for istio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- nameOverride replaces the name of the chart in the Chart.yaml file
nameOverride:
# -- fullnameOverride completely replaces the generated name.
fullnameOverride:

istio:
  # -- Enabled 
  enabled: false
  ## For traffic to the cluster
  ingress:
    # -- (string) The base domain that will be used to construct URLs that point to your API.
    # This should almost always be the Octopus Variable named `DOMAIN` in the 
    # [AWS Access Keys](https://octopus.apps.ops-drivevariant.com/app#/Spaces-22/library/variables/)
    hosts: []
      # - url: "release.apps.dev-drivevariant.com"
      # - url: "release.internal.apps.dev-drivevariant.com"
    # -- Optional paths that will always redirect to internal/VPN endpoints
    redirects:
      - prefix: /hidden
    # Backend Service
    backend:
      service:
        # -- (string) Service Name
        name: test
        # -- (int) port should be number
        port: 1234

  # -- A whitelist of external services that your API requires connection to.
  # The whitelist applies to the entire namespace in which this chart is installed. 
  # [These services](https://github.com/variant-inc/iaac-eks/blob/master/scripts/istio/service-entries.eps#L8) are globally whitelisted and do not require declaration.
  # See [egress](#egress-configuration) for more details.
  egress:
    # ## List of hostnames and ports
    # # Hosts should be FQDN
    # - name:
    #   hosts:
    #     - "test.example.com"
    #   addresses:
    #     - "10.0.0.1"
    #   ports:
    #     - number: 123
    #       ## MUST BE one of HTTP|HTTPS|GRPC|HTTP2|MONGO|TCP|TLS
    #       protocol: HTTPS

serviceMonitor:
  # -- Service Monitor Enabled
  enabled: false
  # -- Service Monitor Target Port
  targetPort: 9090
  # -- Query Interval
  interval: 10s
  # -- Scrape Timeout
  scrapeTimeout: 10s
  # -- (map) Any label selector
  selector: {}
