# Default values for istio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride:
fullnameOverride:

istio:
  enabled: true
  ## For traffic to the cluster
  ingress:
    # Provide only the full hostname
    hosts: 
      - url: "release.internal.apps.dev-drivevariant.com"
      - url: "release.apps.dev-drivevariant.com"
      - url: "release.internal.apps.dev-drivevariant.com"
    # Add endpoints to be rerouted to / in public access
    redirects:
      - prefix: /hidden
    backend:
      service:
        name: test
        ## port should be number
        port: 1234

  ## For external traffic
  egress:
    # ## List of hostnames and ports
    # # Hosts should be FQDN
    # - name:
    #   hosts:
    #     - "test.example.com"
    #   addresses:
    #     - "10.0.0.1"
    #   ports:
    #     - number: 123
    #       ## MUST BE one of HTTP|HTTPS|GRPC|HTTP2|MONGO|TCP|TLS
    #       protocol: HTTPS

serviceMonitor:
  enabled: false
  targetPort: 9090
  interval: 10s
  scrapeTimeout: 10s
  # any label selector
  selector: {}
