{{- $fullName := (include "chart.fullname" .) -}}
{{- $labels := (include "library.chart.labels" .) -}}
{{- $selectorLabels := (include "library.chart.selectorLabels" .) -}}
{{- $podLabels := (include "library.chart.podLabels" .) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
    goldilocks.fairwinds.com/vpa-update-mode: auto
    goldilocks.fairwinds.com/vpa-resource-policy: >
      {"containerPolicies":[{"containerName":"*","minAllowed":{"cpu":"5m","memory":"50Mi"}},{"containerName":"istio-proxy","mode":"Off"}]}
spec:
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- $podLabels | nindent 8 }}
      annotations:
        {{- include "chart.podAnnotations" . | indent 8 }}
    {{- include "library.podspec.tpl" . | nindent 4 }}
