{{- $fullName := (include "chart.fullname" .) -}}
{{- $labels := (include "chart.labels" .) -}}
{{- $host := required "Host is required" .Values.istio.ingress.host -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-internal
  labels: {{ $labels | nindent 4 }}
spec:
  gateways:
    - default/default
  hosts:
    - {{ $fullName }}.internal.apps.{{ $host }}
  http:
    - route:
        - destination:
            host: {{ $fullName }}
            port:
              number: {{ .Values.service.port }}
{{ if .Values.istio.ingress.public }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-public
  labels: {{ $labels | nindent 4 }}
spec:
  gateways:
    - default/default
  hosts:
    - {{ $fullName }}.apps.{{ $host }}
  http:
    - route:
        - destination:
            host: {{ $fullName }}
            port:
              number: {{ .Values.service.port }}
{{ end }}