{{- $fullName := (include "chart.fullname" .) -}}
{{- $labels := (include "library.chart.labels" .) -}}
{{- $host := required "Host is required" .Values.istio.ingress.host -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-internal
  labels: {{ $labels | nindent 4 }}
spec:
  gateways:
    - default/default
  hosts:
    - {{ .Release.Namespace }}-{{ $fullName }}.internal.apps.{{ $host }}
  http:
    - route:
        - destination:
            host: {{ $fullName }}
            port:
              number: {{ .Values.service.port }}
{{ if .Values.istio.ingress.public }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-public
  labels: {{ $labels | nindent 4 }}
spec:
  gateways:
    - default/default
  hosts:
    - {{ .Release.Namespace }}-{{ $fullName }}.apps.{{ $host }}
  http:
    - name: Private Path Redirects
      match:
      {{- if .Values.istio.ingress.redirects}}
        {{- range .Values.istio.ingress.redirects }}
        - uri:
            prefix: {{ .prefix  }}
        {{- end }}
      {{- end }}
        - uri:
            prefix: /health
        - uri:
            prefix: /swagger
        - uri:
            prefix: /swaggerui
      redirect:
        authority: {{ .Release.Namespace }}-{{ $fullName }}.internal.apps.{{ $host }}
        redirectCode: 307
    - name: Default Ingress
      route:
        - destination:
            host: {{ $fullName }}
            port:
              number: {{ .Values.service.port }}
{{ end }}