{{- $fullName := (include "chart.fullname" .) -}}
{{- $service := $fullName }}
{{- if (index .Values "oauth2-proxy").enabled }}
{{- $service = (printf "%s-%s" $fullName "oauth2-proxy" ) }}
{{- end }}
{{- $labels := (include "library.chart.labels" .) -}}
{{- $host := required "Host is required" .Values.istio.ingress.host -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-internal
  labels: {{ $labels | nindent 4 }}
spec:
  gateways:
    - default/default
  hosts:
    - {{ .Release.Namespace }}-{{ $fullName }}.internal.apps.{{ $host }}
    {{- range .Values.istio.ingress.additionalHosts.private }}
    {{- if .prefix }}
    - {{ .prefix }}.internal.{{ $host }}
    {{- end }}
    {{- end }}
  http:
    - route:
        - destination:
            host: {{ $service }}
            port:
              number: {{ .Values.global.upstream.port }}
{{ if .Values.istio.ingress.public }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-public
  labels: {{ $labels | nindent 4 }}
spec:
  gateways:
    - default/default
  hosts:
    - {{ .Release.Namespace }}-{{ $fullName }}.apps.{{ $host }}
    {{- range .Values.istio.ingress.additionalHosts.public }}
    {{- if .prefix }}
    - {{ .prefix }}.{{ $host }}
    {{- end }}
    {{- end }}
  http:
    - name: Private Path Redirects
      match:
      {{- if .Values.istio.ingress.redirects}}
        {{- range .Values.istio.ingress.redirects }}
        - uri:
            prefix: {{ .prefix  }}
        {{- end }}
      {{- end }}
        - uri:
            prefix: /health
        - uri:
            prefix: /swagger
        - uri:
            prefix: /swaggerui
      redirect:
        authority: {{ .Release.Namespace }}-{{ $fullName }}.internal.apps.{{ $host }}
        redirectCode: 307
    - name: Default Ingress
      route:
        - destination:
            host: {{ $service }}
            port:
              number: {{ .Values.global.upstream.port }}
{{ end }}
