---
# Source: variant-api/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: schedule-adherence-api
---
# Source: variant-api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: schedule-adherence-api
  labels:
    helm.sh/chart: variant-api-2.0.0
    app.kubernetes.io/name: variant-api
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    revision: "abc123"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: variant-api
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: variant-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-adherence-api
  labels:
    helm.sh/chart: variant-api-2.0.0
    app.kubernetes.io/name: variant-api
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    revision: "abc123"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: variant-api
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: variant-api
        app.kubernetes.io/instance: RELEASE-NAME
      annotations:
        annotation1: annotation1
        annotation2: annotation2
    spec:
      serviceAccountName: schedule-adherence-api
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 65534
      containers:
        - name: schedule-adherence-api
          image: abc123
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: 1
              memory: 768Mi
            requests:
              cpu: 0.1
              memory: 384Mi
          env:
            - name: REVISION
              value: "abc123"
---
# Source: variant-api/templates/hpa.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: schedule-adherence-api
  labels:
    helm.sh/chart: variant-api-2.0.0
    app.kubernetes.io/name: variant-api
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    revision: "abc123"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: schedule-adherence-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
---
# Source: variant-api/templates/service-entry.yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: schedule-adherence-api-test
  labels: 
    helm.sh/chart: variant-api-2.0.0
    app.kubernetes.io/name: variant-api
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    revision: "abc123"
spec:
  hosts:
    - "test.com"
    - "blah.net"
  exportTo:
    - "."
  location: MESH_EXTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
---
# Source: variant-api/templates/service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels: 
    helm.sh/chart: variant-api-2.0.0
    app.kubernetes.io/name: variant-api
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    revision: "abc123"
  name: schedule-adherence-api
spec:
  endpoints:
    - port: 80
      interval: 10s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - schedule-adherence
  selector: 
    matchLabels:
      app.kubernetes.io/name: variant-api
      app.kubernetes.io/instance: RELEASE-NAME
---
# Source: variant-api/templates/virtual-service.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: schedule-adherence-api-internal
  labels: 
    helm.sh/chart: variant-api-2.0.0
    app.kubernetes.io/name: variant-api
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    revision: "abc123"
spec:
  gateways:
    - default/default
  hosts:
    - api.internal.ops-drivevariant.com
    - api.internal.apps.ops-drivevariant.com
  http:
    - name: Private Ingress
      match:
        - uri:
            prefix: /schedule-adherence/RELEASE-NAME/
      rewrite:
        uri: /
      route:
        - destination:
            host: schedule-adherence-api
            port:
              number: 80
