# This file contains the defaults for all optional, overridable values

istio:
  egress: []
    # - name: some-external-api
    #   hosts:
    #     - "test.example.com"
    #   ports:
    #     - number: 443
    #       protocol: HTTPS
    # - name: some-external-database
    #   addresses:
    #     - "10.0.0.1"
    #   ports:
    #     - number: 5432
    #       protocol: TCP

serviceMonitor:
  # -- Frequency at which Prometheus metrics will be collected from your service
  interval: 10s
  # -- Maximum wait duration for Prometheus metrics response from your service
  scrapeTimeout: 10s

service:
  # -- Port for internal services to access your API
  port: 80
  # -- Port on your container that exposes your HTTP API
  targetPort: 9000
  # -- Optional port which serves a health check endpoint at `/health`
  # Defaults to value of `service.targetPort` if not defined.
  healthCheckPort:
  # -- Optional port which serves prometheus metrics endpoint at `/metrics`
  # Defaults to value of `service.targetPort` if not defined.
  metricsPort:
  # -- Health check URI, This will be used in probes to check container status
  healthCheckPath: /health

serviceAccount:
  # -- (string) Optional ARN of the IAM role to be assumed by your application. 
  # If your API requires access to any AWS services, a role should be created in AWS IAM.
  # This role should have an inline policy that describes the permissions your API needs (connect to RDS, publish to an SNS topic, read from an SQS queue, etc.).
  roleArn:

podSecurityContext:
    # -- Groups of nobody
    fsGroup: 65534

# -- (map) Security Context for containers
securityContext: {}
  # runAsNonRoot: true
  # runAsUser: 1000
  # capabilities:
  #   drop:
  #   - ALL
  # allowPrivilegeEscalation: false
  # readOnlyRootFilesystem: true

# -- replicatCount
replicaCount: 1

autoscaling:
  # -- Flag to trigger HPA, Allowd values true or false
  enabled: false
  # -- Minimum replicas of pod
  minReplicas: 1
  # -- Maximum replicas of pod
  maxReplicas: 5
  # -- (int) CPU Utilization Percentage.
  targetCPUUtilizationPercentage: 80
  # -- (int) Memory Utilization Percentage.
  targetMemoryUtilizationPercentage:

deployment:
  image:
    # -- (string) The full URL of the image to be deployed containing the tag
    tag: "tag"
    # -- (string) IfNotPresent, Always, Never
    pullPolicy: IfNotPresent
  # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/  
  resources:
    limits:
      # -- (int) Limits CPU
      cpu: 1
      # -- (string) Limits Memory
      memory: 768Mi
    requests:
      # -- (float) Requests CPU
      cpu: .1
      # -- (string) Request memory
      memory: 384Mi
  # -- (list) List of arguments that can be passed in the image.
  args: []
  # -- (map) https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  podAnnotations: {}

# -- (string) Value for a [label](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) named `revision` 
# that will be applied to all objects created by a specific chart installation.
# Strongly encouraged that this value corresponds to 1 of: Octopus package version, short-SHA of the commit, Octopus release version
revision: abc

# -- A list of secrets to configure to make available to your API.
# Create your secret in AWS Secrets Manager as plain text.
# Full contents of this secret will be mounted as a file your application can read.
# See [secrets](#secrets) for more details.
awsSecrets: []
  # - name: testKey

# -- (map) User defined secret variables are implemented here.
secretVars: {}
  # foo: bar

# -- (map) User defined environment variables are implemented here.
configVars: {}
  # bar: foo

# -- (map) Node labels for pod assignment
#ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# -- (list) Tolerations for pod assignment
#ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# -- (map) Affinity for pod assignment
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

# -- See [Probe](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Probe) docs
readinessProbe:

# -- See [Probe](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Probe) docs
livenessProbe:

# -- deployment tags
tags:
  # -- Octopus project name
  octopus_project:
  # -- Octopus space name
  octopus_space:
  # -- Octopus environment name
  octopus_environment:
  # -- Octopus project group
  octopus_project_group:
  # -- Octopus release name
  octopus_release_channel:
  # -- Team
  team:
  # -- purpose of the project
  purpose:
  # -- owner of the project
  owner: