# This file contains the defaults for all optional, overridable values

serviceMonitor:
  interval: 10s
  scrapeTimeout: 10s

service:
  port: 80
  targetPort: 9000
  healthCheckPort:
  metricsPort:
  healthCheckPath: /health

serviceAccount:
  roleArn:

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage:

deployment:
  image:
    tag: nginx:latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1
      memory: 768Mi
    requests:
      cpu: .1
      memory: 384Mi
  args: []
  envVars: []
    # - name: required_env_var
    #   value: required_env_var
  conditionalEnvVars: []
    # - condition: false
    #   envVars:
    #     - name: false_conditional
    #       value: false_conditional
    # - condition: true
    #   envVars:
    #     - name: true_conditional_1
    #       value: true_conditional_1
    #     - name: true_conditional_2
    #       value: true_conditional_2
  podAnnotations: {}

secrets: []
  # - name: eng-secret-in-aws
  #   mountPath: /app/secrets
  #   fileName: aws-secret.json

secretsEnvVars: []
  # foo: bar

configsEnvVars: []
  # bar: foo
