# This file contains the defaults for all optional, overridable values

istio:
  egress: []
    # - name: some-external-api
    #   hosts:
    #     - "test.example.com"
    #   ports:
    #     - number: 443
    #       protocol: HTTPS
    # - name: some-external-database
    #   addresses:
    #     - "10.0.0.1"
    #   ports:
    #     - number: 5432
    #       protocol: TCP

serviceAccount:
  roleArn:

cronJob:
  schedule: "*/2 * * * *"
  image:
    pullPolicy: IfNotPresent
    tag: curlimages/curl
  args: []
  podAnnotations: {}
  command: 
    - /bin/echo 
    - Hello from the K8s cluster
  suspend: true

secrets: []
  #- name: eng-secret-in-aws

secretVars:
  foo: bar

configVars:
  bar: foo

revision: "test-latest"

affinity: {}

node:
  create: false

tags:
  owner: platform-infrastructure
  octopus/project: test
  octopus/space: default
  octopus/environment: dev
  octopus/project_group: default group
  octopus/release_channel: test
  team: devops
  purpose: test

securityContext:
  runAsUser: 1001