---
cronJob:
  schedule: "*/2 * * * *"
  image:
    tag: curlimages/curl
  command:
    - /bin/echo
    - Hello from the K8s cluster
  suspend: true

revision: "test-provisioner"

node:
  create: true
  instanceType: t3.medium

tags:
  test: lazy-helm-provisioner-test

securityContext:
  runAsUser: 1001
