---
apiVersion: v2
name: variant-api
description: A Helm chart for APIs to Variant clusters

version: 2.4.0

kubeVersion: "^1.7.1-0"
home: https://www.drivevariant.com/
icon: https://github.com/variant-inc/in-helm-charts/raw/gh-pages/assets/variant-logo.svg
sources:
  - https://github.com/variant-inc
maintainers:
  - name: vibindaniel
    email: vibind@drivevariant.com
  - name: samiralyateem
    email: samira@drivevariant.com

dependencies:
  - name: library
    repository: file://../library
    version: 0.1.0
