---
# Defaults and documentation of chart values

# @ignored
global:
  # -- (map) Deployment tags
  tags: {}

  # @ignored
  # -- (string) Value for a [label](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) named `revision`
  # that will be applied to all objects created by a specific chart installation.
  # Strongly encouraged that this value corresponds to 1 of: Octopus package version, short-SHA of the commit, Octopus release version
  revision:

  # @ignored
  # -- Port for internal services to access your API
  upstream:
    port: 80

istio:
  ingress:
    # @ignored
    # -- (string) The base domain that will be used to construct URLs that point to your API.
    # This should almost always be the Octopus Variable named `DOMAIN` in the
    # [AWS Access Keys](https://octopus.apps.ops-drivevariant.com/app#/Spaces-22/library/variables/).
    # See [Ingress](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/ingress/) for more Istio details.
    host:
    # -- Additional prefixes used to construct URLs that point to your API.
    additionalHosts:
      # -- List of additional private endpoints, accessible only through VPN
      private:
        # -- (string) prefix used to construct the URL, will be appended by `istio.ingress.host` by default
        - prefix:
          # -- (string) optional domain if it has to differ from `istio.ingress.host`.
          # Not yet implemented!
          domain:
      public:
        # -- (string) prefix used to construct the URL, will be appended by `istio.ingress.host` by default
        - prefix:
          # -- (string) optional domain if it has to differ from `istio.ingress.host`.
          # Not yet implemented!
          domain:
    # -- When `false`, an internal URL will be created that will expose your application *via OpenVPN-only*.
    # When `true`, an additional publicly accessible URL will be created.
    # This API should be secured behind some authentication method when set to `true`.
    # See [Ingress](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/ingress/) for more Istio details.
    public: false
    # -- When `true`, the path `/{target-namespace}/{helm-release-name}` will be preserved in requests to your application, else rewritten to `/` when `false`
    disableRewrite: false
    # -- Optional paths that will always redirect to internal/VPN endpoints
    # - prefix: /hidden
    redirects: []
  # -- A whitelist of external services that your application requires connection to.
  # The whitelist applies to the entire namespace in which this chart is installed.
  # [These services](https://github.com/variant-inc/iaac-eks/blob/master/scripts/istio/service-entries.eps#L8) are globally whitelisted and do not require declaration.
  # See [egress](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/egress/) and
  # [Ingress](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/ingress/) for more details.
  egress: []

# This allows prometheus to scrape /metrics endpoint
serviceMonitor:
  # -- Service Monitor Enabled
  enabled: false
  # @ignored
  # -- Query Interval
  interval: 10s
  # @ignored
  # -- Scrape Timeout
  scrapeTimeout: 10s
  # @ignored
  # -- (map) Any label selector
  selector: {}

service:
  # -- Port on your container that exposes your HTTP API
  targetPort: 9000
  # -- Optional port which serves a health check endpoint at `/health`
  # Defaults to value of `service.targetPort` if not defined.
  healthCheckPort:
  # -- Optional port which serves prometheus metrics endpoint at `/metrics`
  # Defaults to value of `service.targetPort` if not defined.
  metricsPort:

# @ignored
serviceAccount:
  # -- (string) Optional ARN of the IAM role to be assumed by your application.
  # If your API requires access to any AWS services, a role should be created in AWS IAM.
  # This role should have an inline policy that describes the permissions your API needs (connect to RDS, publish to an SNS topic, read from an SQS queue, etc.).
  # [RoleArn](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/rolearn/)
  roleArn:

autoscaling:
  # -- (int) Minimum Number of Replicas. [Autoscaling](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/autoscaling/)
  minReplicas: 2
  # -- (int) Maximum Number of Replicas. [Autoscaling](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/autoscaling/)
  maxReplicas: 5
  # -- (int) Number of HTTP Requests Per Second
  httpRequestsPerSecond: 10

deployment:
  image:
    # -- (string) IfNotPresent, Always, Never
    pullPolicy: IfNotPresent
    # -- (string) The full URL of the image to be deployed containing the HTTP API application
    tag:
  # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources:
    limits:
      # -- (int) Limits CPU, intentionally set to null, can't be overridden
      cpu: null
      # -- (string) Limits Memory
      memory: 768Mi
    requests:
      # -- (float) Requests CPU
      cpu: .1
      # -- (string) Request memory
      memory: 384Mi
  # @ignored
  # -- (list) List of arguments that can be passed in the image.
  args: []

  # @ignored
  # -- (list) `deprecated` List of Conditional Env Vars denoted by conditional
  # (bool) and envVars (list)
  # - condition: false
  #   envVars:
  #     - name: false_conditional
  #       value: false_conditional
  conditionalEnvVars: []

# -- (map) [annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/)
podAnnotations: {}

# @ignored
# [Istio RBAC](https://istio.io/v1.3/docs/reference/config/authorization/istio.rbac.v1alpha1/) resources are created
#  to require a valid JWT token before forwarding a request to your API.
# [Ingress](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/ingress/)
authentication:
  tenantId:
  clientId:

# -- (list) List of operation objects with methods and paths key values allowing certain methods and paths to be whitelisted within the cluster
# GET /health and Get /metrics are set by default in authorization.yaml
authorization:
  rules:
    # - operation:
    #     methods: "GET"
    #     paths: "/swagger"
    to: []

# -- A list of secrets to configure to make available to your API.
# Create your secret in AWS Secrets Manager as plain text.
# Full contents of this secret will be mounted as a file your application can read to /app/secrets/{name}
# See [AWS Secrets](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/environment_variables) for more details.
# @default -- Example: `[{ "name": "eng-secret-in-aws", "type": "" }]`
awsSecrets: []

# -- (map) User defined secret variables are implemented here.
# [More Information](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/environment_variables)
# @default -- Example: `foo: bar`
secretVars: {}

# -- (map) User defined environment variables are implemented here.
# [More Information](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/environment_variables)
# @default -- Example: `bar: foo`
configVars: {}

# @ignored
# -- (map) Node labels for pod assignment.
# [NodeSelector](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/nodeselector/)
nodeSelector: {}

# @ignored
# -- (list) Tolerations for pod assignment.
# [Tolerations](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/tolerations/)
tolerations: []

# -- (map) Security Context for pods
podSecurityContext:
  # -- The files created in the container will be created with this gid
  # `65534` is a `nobody` group
  fsGroup: 65534

# -- (map) Security Context for containers
securityContext:
  # -- (int) Runs as numeric user
  runAsUser:
  # -- (int) Runs as numeric user
  runAsGroup:
  # -- Drop All capabilities
  capabilities:
    drop:
      - ALL
  # @ignored
  # -- Runs as non root. Must use numeric User in container
  runAsNonRoot: true
  # @ignored
  # -- (bool) Setting it to false ensures that no child process of a container can gain more privileges than its parent
  allowPrivilegeEscalation: false
  # @ignored
  # -- (bool) Requires that containers must run with a read-only root filesystem (i.e. no writable layer)
  readOnlyRootFilesystem: false

# -- (map) Indicates whether container is ready for requests.
# See [Probe](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/probes/)
readinessProbe: {}
#   httpGet:
#     path: /health
#     port: 5000

# -- (map) Indicates whether container is running.
# See [Probe](https://backstage.apps.ops-drivevariant.com/docs/default/Component/dx-docs/Apps/Common/probes/)
livenessProbe: {}
#   httpGet:
#     path: /health
#     port: 5000

# -- (int) Minimum number of pods that should be available always
# See [Pod Disruption Budget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/)
maxUnavailable: 1

usxpressCACertBundle:
  # -- (bool) If set to true, volume mounts the certificate from the custom-ca-certs secret
  enabled: true
  # -- (string)  The cert is mounted to the default path mentioned. The path can also be changed.
  certMountPath: /etc/ssl/certs/

# @ignored
# For setting up otel sidecar for auto instrumentation
otel:
  # Enable OTel sidecar
  enabled: false
  # Language of the application
  language: sdk
