# Default values for istio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

istio:
  enabled: false
  ## For traffic to the cluster
  ingress:
    # # Should the service be exposed via public ingress gateway?
    public: true
    # # Provide only the full hostname
    host: ops-drivevariant.com

    # Make this as true if you want to handle the rewrite inside the app
    disableRewrite: false

    # Add endpoints to be rerouted to / in public access
    redirects:
      - prefix: /hidden
    # # Should the endpoint be external or internal
    backend:
      service:
        ## These values can be template variables
        # name: {{ .Values.ReleaseName }}
        # port: {{ .Global.service.port }}
        name: test
        ## port should be number
        port: 1234

  ## For external traffic
  egress:
    # ## List of hostnames and ports
    # # Hosts should be FQDN
    # - name:
    #   hosts:
    #     - "test.example.com"
    #   addresses:
    #     - "10.0.0.1"
    #   ports:
    #     - number: 123
    #       ## MUST BE one of HTTP|HTTPS|GRPC|HTTP2|MONGO|TCP|TLS
    #       protocol: HTTPS

serviceMonitor:
  enabled: false
  targetPort: 9090
  interval: 10s
  scrapeTimeout: 10s
  # any label selector
  selector: {}
