# This file contains the defaults for all optional, overridable values

istio:
  ingress:
    public: false
    disableRewrite: false
    redirects: []
      # - prefix: /hidden
  egress: []
    # - name: some-external-api
    #   hosts:
    #     - "test.example.com"
    #   ports:
    #     - number: 443
    #       protocol: HTTPS
    # - name: some-external-database
    #   addresses:
    #     - "10.0.0.1"
    #   ports:
    #     - number: 5432
    #       protocol: TCP

serviceMonitor:
  interval: 10s
  scrapeTimeout: 10s

service:
  port: 80
  targetPort: 9000
  healthCheckPort:
  metricsPort:

serviceAccount:
  roleArn:

autoscaling:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage:

deployment:
  image:
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1
      memory: 768Mi
    requests:
      cpu: .1
      memory: 384Mi
  args: []
  envVars: []
    # - name: required_env_var
    #   value: required_env_var
  conditionalEnvVars: []
    # - condition: false
    #   envVars:
    #     - name: false_conditional
    #       value: false_conditional
    # - condition: true
    #   envVars:
    #     - name: true_conditional_1
    #       value: true_conditional_1
    #     - name: true_conditional_2
    #       value: true_conditional_2
  podAnnotations: {}

secrets: []
  # - name: eng-secret-in-aws
  #   mountPath: /app/secrets
  #   fileName: aws-secret.json

authentication:
  enabled: true
  server: trustme.com

authorization:
  rules:
    to:
      - operation:
          methods: "GET"
          paths: "/swagger"
