nameOverride: ""
fullnameOverride: ""
revision: 

istio:
  ingress:
    public: false
    host: ops-drivevariant.com
    disableRewrite: false

    # Add endpoints to be rerouted to / in public access
    redirects:
      - prefix: /hidden

  egress: []
    # - name: some-external-api
    #   hosts:
    #     - "test.example.com"
    #   ports:
    #     - number: 443
    #       protocol: HTTPS
    # - name: some-external-database
    #   addresses:
    #     - "10.0.0.1"
    #   ports:
    #     - number: 5432
    #       protocol: TCP

serviceMonitor:
  interval: 10s
  scrapeTimeout: 10s

service:
  # Port # exposed by the Kubernetes Service which will point to your deployed Pods
  port: 80
  # Port # that exposes your HTTP application in your image
  targetPort: 9000

autoscaling:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

serviceAccount:
  # SET via terrform syntax {alias}.serviceAccount.roleArn if AWS permissions are required
  roleArn:

deployment:
  image:
    # SET via terrform syntax {alias}.image.tag
    tag:
    pullPolicy: Always

  resources:
    limits:
      cpu: 1
      memory: 768Mi
    requests:
      cpu: .1
      memory: 384Mi

  # SET via terraform syntax {alias}.args[0], {alias}.args[1], etc. for the number of args required
  args: []

  # SET via terraform syntax in pairs of {alias}.envVars[0].name, {alias}.envVars[0].value
  envVars: []
