{{- $fullName := (include "library.chart.fullname" .) -}}
{{- $labels := (include "library.chart.labels" .) -}}
{{- if (index .Values "oauth2-proxy").enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-oauth2-secret
  labels:
    {{- $labels | nindent 4 }}
type: Opaque
stringData:
  client_secret: {{ (index .Values "oauth2-proxy").config.clientSecret }}
{{- end }}