{{- $fullName := (include "library.chart.fullname" .) -}}
{{- $labels := (include "library.chart.labels" .) -}}
{{- if (index .Values "oauth2-proxy").enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-oauth2-alpha
  labels:
    {{- $labels | nindent 4 }}
data:
  oauth2_proxy.yml: |
    ---
    server:
      BindAddress: '0.0.0.0:4180'
    injectRequestHeaders:
      - name: x-forwarded-roles
        values:
          - claim: groups
      - name: x-forwarded-email
        values:
          - claim: email
      - name: x-forwarded-refresh-token
        values:
          - claim: refresh_token
      - name: x-forwarded-id-token
        values:
          - claim: id_token
      - name: x-forwarded-access-token
        values:
          - claim: access_token
      - name: x-forwarded-userinfo-endpoint
        values:
          - value: aHR0cHM6Ly9ncmFwaC5taWNyb3NvZnQuY29tL29pZGMvdXNlcmluZm8=
      - name: authorization
        values:
          - claim: access_token
            prefix: "Bearer "
    providers:
      - azureConfig:
          graphGroupField: displayName
          tenant: {{ (index .Values "oauth2-proxy").config.tenantId }}
        clientID: {{ (index .Values "oauth2-proxy").config.clientId }}
        clientSecretFile: /secrets/client_secret
        id: azure:{{ (index .Values "oauth2-proxy").config.clientId }}
        profileURL: https://graph.microsoft.com/oidc/userinfo
        loginURLParameters:
          - default:
              - force
            name: approval_prompt
        name: USXpress
        oidcConfig:
          audienceClaims:
            - aud
          emailClaim: email
          groupsClaim: roles
          insecureAllowUnverifiedEmail: true
          issuerURL: https://login.microsoftonline.com/{{ (index .Values "oauth2-proxy").config.tenantId }}/v2.0
          userIDClaim: email
        provider: oidc
        scope: openid profile email offline_access {{ (index .Values "oauth2-proxy").config.clientId }}/.default
    upstreamConfig:
      upstreams:
        - id: service
          path: /
          uri: http://{{ $fullName }}:80
{{- end }}
