deployment:
  image:
    tag: 064859874041.dkr.ecr.us-east-2.amazonaws.com/lazy-helm-charts/variant-api:v0.4
revision: testing

istio:
  enabled: true
  ingress:
    host: dpl-drivevariant.com
service:
  targetPort: 5000

configVars:
  PLAIN_CONFIG: foo

secretVars:
  SECRET_CONFIG: secret
  SOMETHING: else

configMaps:
  - test-existing

awsSecrets:
  - name: devops-playground-rds-creds
    reference: rdscreds
  - name: postgres-secret-backstage
    reference: backstage_postgres

livenessProbe:
  httpGet:
    path: /health
    port: 5000

readinessProbe:
  httpGet:
    path: /health
    port: 5000

tags:
  octopus/project: test
  octopus/pace: default
  octopus/environment: dev
  octopus/project_group: default group
  octopus/release_channel: test1
  team: devops
  purpose: test
  owner: devops

usxpressCACertBundle:
  enabled: true
