deployment:
  image:
    tag: 064859874041.dkr.ecr.us-east-2.amazonaws.com/lazy-helm-charts/variant-api:v0.3
revision: testing

istio:
  enabled: true
  ingress:
    host: dpl-drivevariant.com
service:
  targetPort: 5000

configVars:
  PLAIN_CONFIG: foo

secretVars:
  SECRET_CONFIG: secret
  SOMETHING: else

configMaps:
  - test-existing

awsSecrets:
  - name: devops-playground-rds-creds


livenessProbe:
  httpGet:
    path: /health
    port: 5000

readinessProbe:
  httpGet:
    path: /health
    port: 5000

tags:
  # -- Octopus tags
  octopusTags:
    # -- Octopus project name
    project: test
    # -- Octopus space name
    space: default
    # -- Octopus environment name
    environment: dev
    # -- Octopus project group
    project_group: default group
    # -- Octopus release name
    release_channel: test

  # -- User tags
  userTags:
    # -- Team
    team: devops
    # -- purpose of the project
    purpose: test
    # -- owner of the project
    owner: devops