deployment:
  image:
    tag: 064859874041.dkr.ecr.us-east-2.amazonaws.com/lazy-helm-charts/variant-api:v0.3
revision: testing
istio:
  ingress:
    public: true
    host: dpl-drivevariant.com
  egress:
    - name: google
      hosts:
        - "google.com"
      ports:
        - number: 443
          protocol: HTTPS
service:
  targetPort: 5000
authentication:
  enabled: true
  server: trustme.com
authorization:
  rules:
    to:
      - operation:
          methods: "GET"
          paths: "/swagger"
tags:
  octopus_tags:
    project: test
    space: default
    environment: dev
    project_group: default group
    release_channel: test
  user_tags:
    team: devops
    purpose: test
    owner: devops



