suite: Chart defaults
tests:
  - it: should be internal only
    release:
      name: test
    set:
      deployment.image.tag: tag
      revision: abc
      tags:
        owner: platform-infrastructure
        octopus/project: test
        octopus/space: default
        octopus/environment: dev
        octopus/project_group: default group
        octopus/release_channel: test
        team: devops
        purpose: test
      livenessProbe:
        exec:
          command:
            - /bin/echo
            - "hello liveness"
      readinessProbe:
        exec:
          command:
            - /bin/echo
            - "hello readiness"
    asserts:
      - template: deployment.yaml
        containsDocument:
          kind: Deployment
          apiVersion: apps/v1
          name: test
      - template: deployment.yaml
        hasDocuments:
          count: 1
