suite: Chart defaults
tests:
  - it: should be internal only
    release:
      name: test
    set:
      deployment.image.tag: tag
      revision: abc
      tags:
        octopus_tags:
          project: test
          space: default
          environment: dev
          project_group: default group
          release_channel: test
        user_tags:
          team: devops
          purpose: test
          owner: devops
      livenessProbe:
        exec:
          command:
            - /bin/echo
            - "hello liveness"
      readinessProbe:
        exec:
          command:
            - /bin/echo
            - "hello readiness"
    asserts:
      - template: deployment.yaml
        containsDocument:
          kind: Deployment
          apiVersion: apps/v1
          name: test
      - template: deployment.yaml
        hasDocuments:
          count: 1