name: Branch CI

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: eks
    name: CI
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lazy Actions Setup
        id: lazy-setup
        uses: variant-inc/actions-setup@v1
      - name: Pre-commit
        run: pre-commit run -a --show-diff-on-failure
      # TODO - Re-enable linting after cluster is upgraded to 1.22+
      # - name: Lint
      #   run: |
      #     helm lint --strict ./charts/*
      - name: Unit Test
        shell: pwsh
        run: ./scripts/unit_test.ps1
      - name: Lazy Action Octopus
        uses: variant-inc/actions-octopus@v2
        with:
          default_branch: master
          version: ${{ steps.lazy-setup.outputs.image_version }}
          charts_dir_path: charts/variant-api
