---
# yamllint disable rule:line-length
name: Pre-Commit

on:  # yamllint disable-line rule:truthy
  push:

jobs:
  preCommit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pre-commit dependencies
        run: |
          for i in `find charts -name Chart.yaml | sed 's/Chart.yaml//g'`;
            do helm dependency update --skip-refresh "$i";
          done

          mkdir -p "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

          HELM_DOCS_TAR=$(curl -sfSL https://api.github.com/repos/norwoodj/helm-docs/releases/latest | grep -o -E "https://.+?Linux_x86_64.tar.gz")
          curl -sfSL "$HELM_DOCS_TAR" > helm-docs.tar.gz
          tar -xvf helm-docs.tar.gz -C $HOME/.local/bin
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
