---
name: Release Charts

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          mark_as_latest="false"
          if [ "${GITHUB_REF##*/}" == "master" ]; then
              mark_as_latest="true"
          fi
          echo "mark_as_latest=$mark_as_latest" >>"$GITHUB_ENV"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        # with:
        #   mark_as_latest: ${{ env.mark_as_latest }}
