name: Release Charts

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: variant-inc/actions-setup@v2

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          mark_as_latest="false"
          if [ "${GITVERSION_PRERELEASELABEL}" == "" ]; then
              mark_as_latest="true"
          fi
          echo "mark_as_latest=$mark_as_latest" >>"$GITHUB_ENV"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@main
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
        with:
          mark_as_latest: ${{ env.mark_as_latest }}
