revision: testing
deployment:
  image:
    tag: 064859874041.dkr.ecr.us-east-2.amazonaws.com/lazy-helm-charts/variant-api:v0.3

service:
  targetPort: 5000

istio:
  enabled: true
  ingress:
    host: dpl-drivevariant.com

livenessProbe:
  exec:
    command:
      - /bin/echo
      - "hello liveness"

readinessProbe:
  exec:
    command:
      - /bin/echo
      - "hello liveness"

configVars:
  foo: bar
  color: blue

tags:
  octopusTags:
    # -- Octopus project name
    project: test
    # -- Octopus space name
    space: default
    # -- Octopus environment name
    environment: dev
    # -- Octopus project group
    project_group: default group
    # -- Octopus release name
    release_channel: test

  # -- User tags
  userTags:
    # -- Team
    team: devops
    # -- purpose of the project
    purpose: test
    # -- owner of the project
    owner: devops
