---
revision: testing
deployment:
  image:
    tag: 064859874041.dkr.ecr.us-east-2.amazonaws.com/lazy-helm-charts/variant-api:v0.3

service:
  targetPort: 5000

istio:
  enabled: true
  ingress:
    host: dpl-drivevariant.com

livenessProbe:
  exec:
    command:
      - /bin/echo
      - "hello liveness"

readinessProbe:
  exec:
    command:
      - /bin/echo
      - "hello liveness"

configVars:
  foo: bar
  color: blue

tags:
  owner: platform-infrastructure
  octopus/project: test
  octopus/space: default
  octopus/environment: dev
  octopus/project_group: default group
  octopus/release_channel: test
  team: devops
  purpose: test
