{{- if .Values.authentication.clientId }}
{{- $fullName := (include "chart.fullname" .) -}}
{{- $labels := (include "library.chart.labels" .) -}}
{{- $selectorLabels := (include "library.chart.selectorLabels" .) -}}
{{- $host := (include "chart.ingressHostname" .) -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
    - from:
        - source:
            notPrincipals: ["cluster.local*"]
      to:
        - operation:
            methods: ["GET"]
            paths:
              - "/health"
              - "{{ .Release.Namespace }}/{{ .Release.Name }}/health"
        - operation:
            methods: ["GET"]
            paths:
              - "/metrics"
              - "{{ .Release.Namespace }}/{{ .Release.Name }}/metrics"
        - operation:
            methods: ["GET"]
            paths:
              - "/swagger*"
              - "{{ .Release.Namespace }}/{{ .Release.Name }}/swagger*"
    {{- if .Values.authorization.rules.to }}
    {{- range  .Values.authorization.rules.to }}
    {{- if and (ne .operation.paths "/*") (ne .operation.paths "*") }}
        - operation:
            methods: [{{ .operation.methods | quote }}]
            paths: [{{ .operation.paths | quote }}]
    {{- end }}
    {{- end }}
    {{- end }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $fullName }}-auth-internal-test
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    {{- $labels | nindent 4 }}
  namespace: "lazy-helm-charts-tests"
spec:
  restartPolicy: Never
  containers:
    - name: curl
      image: curlimages/curl:7.81.0
      env:
        - name: fullname
          value: {{ $fullName }}
      args: ["-s", "-i", "-v", "-L", "--fail-with-body", "-X", "GET", "http://$(fullname).lazy-helm-charts/health"]
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $fullName }}-auth-external-test
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": hook-succeeded
  namespace: "lazy-helm-charts-tests"
  labels:
    {{- $labels | nindent 4 }}
spec:
  restartPolicy: Never
  containers:
    - name: bash
      image: ellerbrock/alpine-bash-curl-ssl
      env:
        - name: FULLNAME
          value: api.{{ $host }}/{{ .Release.Namespace }}/{{ .Release.Name }}/
      command: ["/bin/sh", "-c"]
      args:
        - export FULLNAME=$(FULLNAME);
          echo $FULLNAME;
          STATUS=$(curl -s -L -w "%{http_code}" -o /dev/null -X GET $FULLNAME);
          echo "$STATUS";
          if [ "$STATUS" -ne 403 ];
          then echo $STATUS && exit 1;
          fi;
{{- end }}
