{{- if .Values.authentication.clientId }}
{{- $fullName := (include "chart.fullname" .) -}}
{{- $labels := (include "library.chart.labels" .) -}}
{{- $selectorLabels := (include "library.chart.selectorLabels" .) -}}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  jwtRules:
    - audiences:
        - {{ .Values.authentication.clientId }}
      issuer: >-
        https://login.microsoftonline.com/{{ .Values.authentication.tenantId }}/v2.0
      jwksUri: >-
        https://login.microsoftonline.com/{{ .Values.authentication.tenantId }}/discovery/keys
      outputClaimToHeaders:
        - claim: roles
          header: x-forwarded-roles
        - claim: groups
          header: x-forwarded-groups
        - claim: preferred_username
          header: x-forwarded-preferred-username
        - claim: name
          header: x-forwarded-name
        - claim: email
          header: x-forwarded-email
{{- end }}
