{{- $fullName := (include "chart.fullname" .) -}}
{{- $labels := (include "chart.labels" .) -}}
{{- $selectorLabels := (include "chart.selectorLabels" .) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- $selectorLabels | nindent 8 }}
    spec:
      serviceAccountName: {{ required "serviceAccount.name is required" .Values.serviceAccount.name }}
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 65534
      containers:
        - name: {{ $fullName }}
          image: {{ required "image.tag is required" .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if len .Values.args }}
          args: 
          {{- range .Values.args }}
            - {{ . }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ required "Target Port is required" .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if len .Values.envVars }}
          env:
          {{- range .Values.envVars }}
            - name: {{ required ".name is required for all envVars" .name }}
              value: {{ required ".value is required for all envVars" .value }}
          {{- end }}
          {{- end }}
