---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "chart.fullname" . }}-env
  labels:
    {{- include "chart.labels" . | nindent 4 }}
stringData:
  {{- range $key, $value := .Values.secretVars }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
type: Opaque