{{- $fullName := (include "chart.fullname" .) -}}
{{- $labels := (include "chart.labels" .) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}
  {{- if .Values.serviceAccount.roleArn }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    "eks.amazonaws.com/role-arn": "{{ .Values.serviceAccount.roleArn }}" 
  {{- end }}
