{{- if .Values.serviceMonitor.enabled }}
{{- $selectorLabels := (include "chart.selectorLabels" .) -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels: {{ include "chart.labels" . | nindent 4 }}
  name: {{ include "chart.fullname" . }}
spec:
  endpoints:
    - targetPort: {{ default 9090 .Values.service.targetPort }}
      port: {{ default "metrics" .Values.service.port }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector: 
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
{{- end }}