{{- if .Values.istio.ingress.public }}
{{- $fullName := (include "chart.fullname" .) -}}
{{- $labels := (include "chart.labels" .) -}}
{{- $release := .Release -}}
{{- $host := (include "chart.ingressHostname" .) -}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  labels: {{ $labels | nindent 4 }}
spec:
  gateways:
    - default/default
  hosts:
    - api.{{ $host }}
    - api.apps.{{ $host }}
  http:
    - name: Private Path Redirects
      match:
      {{- if .Values.istio.ingress.redirects}}
        {{- range .Values.istio.ingress.redirects }}
        - uri:
            prefix: /{{ $release.Namespace }}/{{ $release.Name }}{{ .prefix  }}
        {{- end }}
      {{- end }}
        - uri:
            prefix: /{{ $release.Namespace }}/{{ $release.Name }}/health
        - uri:
            prefix: /{{ $release.Namespace }}/{{ $release.Name }}/docs
        - uri:
            prefix: /{{ $release.Namespace }}/{{ $release.Name }}/redoc
        - uri:
            prefix: /{{ $release.Namespace }}/{{ $release.Name }}/swagger
        - uri:
            prefix: /{{ $release.Namespace }}/{{ $release.Name }}/swaggerui
      redirect:
        authority: api.internal.apps.{{ $host }}
        redirectCode: 307
    - name: Default Ingress
      match:
        - uri:
            prefix: /{{ $release.Namespace }}/{{ $release.Name }}/
      {{ if not .Values.istio.ingress.disableRewrite -}}
      rewrite:
        uri: /
      {{ end -}}
      route:
        - destination:
            host: {{ $fullName }}
            port:
              number: {{ .Values.service.port }}
{{- end -}}