{{- if .Values.istio.enabled -}}
{{- $fullName := (include "chart.fullname" .) -}}
{{- $labels := (include "chart.labels" .) -}}
{{- $release := .Release -}}
{{- if .Values.istio.ingress }}
{{- if .Values.istio.ingress.public }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  labels: {{ $labels | nindent 4 }}
spec:
  gateways:
    - default/default
  hosts:
    - api.{{ .Values.istio.ingress.host }}
    - api.apps.{{ .Values.istio.ingress.host }}
  http:
    - name: Private Path Redirects
      match:
      {{- if .Values.istio.ingress.redirects}}
        {{- range .Values.istio.ingress.redirects }}
        - uri:
            prefix: /{{ $release.Namespace }}/{{ $release.Name }}{{ .prefix  }}
        {{- end }}
      {{- end }}
        - uri:
            prefix: /{{ $release.Namespace }}/{{ $release.Name }}/health
        - uri:
            prefix: /{{ $release.Namespace }}/{{ $release.Name }}/docs
        - uri:
            prefix: /{{ $release.Namespace }}/{{ $release.Name }}/redoc
        - uri:
            prefix: /{{ $release.Namespace }}/{{ $release.Name }}/swagger
        - uri:
            prefix: /{{ $release.Namespace }}/{{ $release.Name }}/swaggerui
      redirect:
        authority: api.internal.apps.{{ .Values.istio.ingress.host }}
        redirectCode: 307
    - name: Default Ingress
      match:
        - uri:
            prefix: /{{ $release.Namespace }}/{{ $release.Name }}/
      {{- if not .Values.istio.ingress.disableRewrite }}
      rewrite:
        uri: /
      {{- end -}}
      route:
        - destination:
            host: {{ tpl .Values.istio.ingress.backend.service.name $ }}
            port:
              number: {{ int (tpl (.Values.istio.ingress.backend.service.port | toString) $) }}
{{- end -}}
{{- end -}}
{{- end -}}
